###   INDICE PRINCIPAL
GET http://localhost:3434/api

### OBTENER TODAS LAS CARTAS ASTRALES

GET http://localhost:3434/api/charts

### OBTENER TODOS LOS USUARIOS

GET http://localhost:3434/api/users

### OBTENER UNA CARTA ASTRAL POR NOMBRE

GET http://localhost:3434/api/charts/matias arno

### OBTENER UN USUARIO POR ID

GET http://localhost:3434/api/users/0ac7be2d-cddb-4558-a687-4d21b7be7e85

### AGREGAR UNA CARTA ASTRAL

POST http://localhost:3434/api/charts
Content-Type: application/json

{
"name": "test 4",
"birthdate": "1-5-12",
"time": 2123,
"asc": 214,
"sun": 347,
"moon": 332,
"mercury": 344,
"venus": 341,
"mars": 180,
"jupiter": 310,
"saturn": 7,
"uranus": 306,
"neptune": 299,
"pluto": 245
}

### AGREGAR/DAR DE ALTA UN NUEVO USUARIO

POST http://localhost:3434/api/users/
Content-Type: application/json

{
"name": "luciana",
"email": "luciarod@gmail.com"
}

### MODIFICAR UNO O VARIOS DATOS DE LA CARTA ASTRAL

PATCH http://localhost:3434/api/charts/Matias Arno
Content-Type: application/json

{
"birthdate": "7-3-2000"
}

### MODIFICAR UNO O VARIOS DATOS DE USUARIOS

PATCH http://localhost:3434/api/users/f81484be-e6a8-49dd-9b9e-3fe0c1c7395b
Content-Type: application/json

{
    "email": "luciagonz@gmail.com"
}

### BORRAR UNA CARTA ASTRAL

DELETE http://localhost:3434/api/charts/test 1

### BORRAR UN USUARIO 

DELETE http://localhost:3434/api/users/8081bdd0-21fb-41b8-a47c-aa1232306a31