###   INDICE PRINCIPAL
GET http://localhost:3434/api

### OBTENER TODAS LAS CARTAS ASTRALES

GET http://localhost:3434/api/charts

### OBTENER TODOS LOS USUARIOS

GET http://localhost:3434/api/users

### OBTENER UNA CARTA ASTRAL POR NOMBRE

GET http://localhost:3434/api/charts/matias arno

### OBTENER UN USUARIO POR ID

GET http://localhost:3434/api/users/0ac7be2d-cddb-4558-a687-4d21b7be7e85

### AGREGAR UNA CARTA ASTRAL

POST http://localhost:3434/api/charts
Content-Type: application/json

{
      "name": "test 4",
      "birthdate": "1-5-12",
      "time": 2123,
      "asc": 214,
      "sun": 347,
      "moon": 332,
      "mercury": 344,
      "venus": 341,
      "mars": 180,
      "jupiter": 310,
      "saturn": 7,
      "uranus": 306,
      "neptune": 299,
      "pluto": 245
    }