### Indice 

GET http://localhost:3434/api

### obtener todos los cartas astrales

GET http://localhost:3434/api/charts

### obtener todos los usuarios

GET http://localhost:3434/api/users

### Obtener una carta natal ingresando un nombre

GET http://localhost:3434/api/charts/matias arno

### Buscar un usuario por id

GET http://localhost:3434/api/users/0ac7be2d-cddb-4558-a687-4d21b7be7e85
